export const GET_TEN_PLAYERS = 'GET_TEN_PLAYERS'
export const LOGIN_OR_CREATE = 'LOGIN_OR_CREATE'
export const GET_TEST = 'GET_TEST'
export const ADD_TEST = 'ADD_TEST'
// export const API_URL = 'http://localhost:8080'
export const API_URL = 'https://develop.delosandes.xyz'
export const API_PORT = '3030'