export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS'
export const GET_TEST = 'GET_TEST'
export const ADD_TEST = 'ADD_TEST'
// export const API_URL = 'http://localhost:8080'
export const API_URL = 'https://develop.delosandes.xyz'
export const API_PORT = '3030'